apiVersion: v1
kind: Secret
metadata:
  name: fraud-platform-secrets
  labels:
    {{- include "fraud-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.secrets.postgres.username | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  kafka-bootstrap-servers: {{ .Values.secrets.kafka.bootstrapServers | quote }}
  redis-host: {{ .Values.secrets.redis.host | quote }}
  redis-port: {{ .Values.secrets.redis.port | quote }}
  rules-analyst-password: {{ .Values.secrets.rulesAnalystPassword | default "analyst" | quote }}
