spring:
  application:
    name: rules-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/frauddb}
    username: ${SPRING_DATASOURCE_USERNAME:fraud}
    password: ${SPRING_DATASOURCE_PASSWORD:fraud}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: ${RULES_ANALYST_USER:analyst}
      password: ${RULES_ANALYST_PASSWORD:analyst}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: rules-service
