spring:
  application:
    name: rules-service
  datasource:
    url: jdbc:postgresql://localhost:5432/frauddb
    username: fraud
    password: fraud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: analyst
      password: analyst

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: rules-service
